name: Build Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Flutter环境
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: 获取Flutter依赖
      run: flutter pub get
      
    - name: 分析代码
      run: flutter analyze
      
    - name: 运行测试
      run: flutter test
      
    - name: 检查代码格式
      run: dart format --set-exit-if-changed .

  build-android:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Java环境
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: 设置Flutter环境
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: 获取Flutter依赖
      run: flutter pub get
      
    - name: 构建Android APK
      run: flutter build apk --debug
      
    - name: 上传APK构建产物
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
        retention-days: 7

  build-windows:
    runs-on: windows-latest
    needs: test
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Flutter环境
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: 获取Flutter依赖
      run: flutter pub get
      
    - name: 构建Windows应用
      run: |
        flutter config --enable-windows-desktop
        flutter build windows --debug
        
    - name: 压缩Windows构建产物
      run: |
        Compress-Archive -Path "build\windows\x64\runner\Debug\*" -DestinationPath "windows-debug.zip"
      shell: powershell
      
    - name: 上传Windows构建产物
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: windows-debug.zip
        retention-days: 7
